@startuml Browse Jobs Activity Diagram
title Browse Jobs Activity Diagram

start

:Navigate to Jobs Page;
:Enter search criteria;
:Retrieve job listings from /jobs;

if (At least one listing found?) then (yes)

    while (More jobs to show?)
        :Display job details tile;
        
        if ("Apply Clicked") then (yes)
            :Submit application to /apply;
            :Display confirmation;
        endif

    endwhile

endif

stop

@enduml
