@startuml Register Account Activity Diagram
title Sign-Up Activity Diagram

start

:Visit Home Page;

:Click "Sign In";

:Fill out Sign-Up form;

:Submit Sign-Up data to /sign-up;

if (User selected Sign-up as Employer option?) then (yes)
    :Create new employer account in DB;
else
    :Create new job seeker account in DB;
endif

:API confirms account creation;

:Display registration confirmation message;

stop

@enduml