@startuml Sign-In Activity Diagram
title Sign-In Activity Diagram

start

:Visit Home Page;
:Click "Sign In";
:Enter Emailid and Password;
:Submit credentials /sign-in;

:Verify credentials in DB;
:API returns verification result;

if (Credentials are valid?) then (yes)
    :Display Profile page;
else
    :Display error message;
endif

stop

@enduml
